## Kevin Kirby Discussion Board Week 6 Submission

1. What are the similarities and differences between pandas and numpy?   Include some type of example with code.

Answer:

Similarities:

* Pandas is built on top of NumPy, which enables data structures like Series and DataFrames
* You can use broadcasting, where operations can be performed across data structures of different shapes
* Both allow for vectorized operations, which are often magnitudes more efficient than applying functions element-wise

Differences:

* NumPy arrays are homogeneous, where all elements must be of the same type, while pandas DataFrames can contain mixed data types.
* NumPy is generally used for math-intensive computations while Pandas is more oriented around data manipulation and analysis.
* NumPy arrays are more basic and have fewer features compared to pandas DataFrames. The flip side is they're easier to transform into other data structures.




In [3]:
import numpy as np
import pandas as pd

# Pandas DataFrame: allows mixed types (string and numerical)
#A pandas dataframe supporting multiple data types: words, letters, and numbers
panda_df = pd.DataFrame({'Product': ['A', 'B', 'C'], 'Price': [10, 15, 20]})
print("panda_df: \n" , panda_df)

# two different arays with two different data types. It doesn't have to be nummbers, just the same type.
num_array = np.array([10, 15, 20])
word_array = np.array(['cars', 'bikes', 'trucks'])
print("\nnum array: \n", num_array)
print("\nword array: \n", word_array)


panda_df: 
   Product  Price
0       A     10
1       B     15
2       C     20

num array: 
 [10 15 20]

word array: 
 ['cars' 'bikes' 'trucks']


2. What is the ndarray in numPy?

Answer:

An ndarray is a multi-dimensional array object, which is a container for data of the same type. It is similar to a list, but it can hold any data type and is optimized for intensive calculations, like vectorization. Matrices are made by placing rows of numbers inside square brackets, which are house in square brackets that encompass the entire array. 



In [8]:
#3x3 matrix as a 2d array
two_dimension_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing attributes of ndarray

#print the whole array
print("matrix as array:\n", two_dimension_matrix, "\n")

#print the shape, which will be (3,3)
print("shape:", two_dimension_matrix.shape)     

#print the data type, which will be int64
print("Data type:", two_dimension_matrix.dtype)       
#print the number of dimensions, which will be 2
print("Number of dimensions:", two_dimension_matrix.ndim)  

matrix as array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

shape: (3, 3)
Data type: int64
Number of dimensions: 2


3. Create a 1D array of numbers from 0 to 9 

Desired Output: 
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Answer:

In [9]:
count_off = np.arange(10)
print(count_off)

[0 1 2 3 4 5 6 7 8 9]


4. Extract all odd numbers from array1:
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Answer:
This is done by using the math code symbol for returning the remainer of a division, %. If you do % 2 !=0, the number is odd of there's a remainer.

In [10]:
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_one_out = array1[array1 % 2 != 0]
print(odd_one_out)

[1 3 5 7 9]


5. Get the common items between a and  b  
#input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Answer:
Uses numpy's intersect1d function to find the common items between the two arrays.

In [11]:
# provided input arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# intersect1d extraction
common_items = np.intersect1d(a, b)
print(common_items)

[2 4]


6. From array a remove all items present in array  b 
#Input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Answer:
Uses numpy's setdiff1d function returns the unique and sorted values in one array that are not present in another array. This is also know as finding the set difference.


In [15]:
# Inputs
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

#
result = np.setdiff1d(a, b)
print("result: ", result)
print("a: ", a)
print("b: ", b)

result:  [1 2 3 4]
a:  [1 2 3 4 5]
b:  [5 6 7 8 9]


7. Find out if iris has any missing values.
Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Answer: 
I was running into an SSL certificate error due to the srtructure of the website so I changed te approach slightly to get around this.

I still ended up where I wanted to be, which was using numpy's isnan function to check for missing values.

In [21]:
import requests
from io import StringIO

# proivded url 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

#use a get request with verify=false to disable SSL certificate verification
response = requests.get(url, verify=False)

#stringiIO converts the response text-file style document
iris_data = StringIO(response.text)

#loads only the numeric columns into array, dropping the species column
iris = np.genfromtxt(iris_data, delimiter=',', usecols=[0, 1, 2, 3])

print(iris)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

/Users/uwsthoughts/venv-metal/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'archive.ics.uci.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
